### PR TITLE
Fix den_x <-> den_z swap

### LINKED ISSUE #1: DEN_Z and DEN_X swapped
Hello,

This line
https://github.com/STMicroelectronics/lsm6dsr-pid/blob/814a2608e3ec715f219ca0ca585c46901fbaaf53/lsm6dsr_reg.c#L8171
references den_z, but it is part of the function lsm6dsr_den_mark_axis_x_set()

X and Z axis are inverted.

### PR DESCRIPTION
**Pull request by philfifi**
Closes #1

(with the CLA signed now :-) )

### CODE REVIEW

File: lsm6dsr_reg.c [hunk 1]
```diff
@@ -7369,20 +7369,19 @@ int32_t lsm6dsr_batch_counter_threshold_get(const stmdev_ctx_t *ctx,
   */
 int32_t lsm6dsr_fifo_data_level_get(const stmdev_ctx_t *ctx, uint16_t *val)
 {
+  lsm6dsr_reg_t reg[2];
   lsm6dsr_fifo_status1_t fifo_status1;
   lsm6dsr_fifo_status2_t fifo_status2;
```
Comment (avisconti) [inline lsm6dsr_reg.c]: Are those two still used?

**Review by avisconti — CHANGES_REQUESTED** [review]
Looks almost good to me. Please just take a look at my feedback

File: lsm6dsr_reg.c (hunk 1 above)
Comment (philfifi) [reply lsm6dsr_reg.c]: Oups,
1. The commit you reviewed was not meant to be part of this MR (i removed it)
2. You are right, those 2 variables are unnecessary. I'll make another independant MR for it #4
Thanks

**Review by avisconti — APPROVED** [review]

**Review by avisconti — APPROVED** [review]
